# Generated by Django 5.0.2 on 2024-02-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='p_phone',
            field=models.CharField(max_length=10),
        ),
    ]
