# Generated by Django 5.0.2 on 2024-02-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_rename_booking_bookings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
    ]
